version: '3'

services:

  front:
    build: ./front/
    working_dir: /opt/app
    volumes:
    - ./front/:/opt/app
    ports:
    - '4200:4200'
    depends_on:
    - mongo

  mongo:
    image: mongo
    restart: always
    ports:
    - '27017:27017'
